name: Sync www directory to www branch

on:
  push:
    branches:
      - master

jobs:
  sync-www:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up git
        run: |
          git config --global user.name 'Wuqiyang312'
          git config --global user.email 'wuqiyang312@163.com'
      
      - name: Fetch all branches
        run: git fetch origin

      - name: Clone www branch or create if not exists
        run: |
          if git ls-remote --exit-code --heads origin www; then
            git clone --branch www https://github.com/Wuqiyang312/firmware-selector-wqyblog-cn.git www-repo
          else
            git clone https://github.com/Wuqiyang312/firmware-selector-wqyblog-cn.git www-repo
            cd www-repo
            git checkout --orphan www
            git rm -rf .
            git commit --allow-empty -m "Initialize www branch"
            git push origin www
            cd ..
          fi

      - name: Copy /www/ directory
        run: |
          cp -r www/* www-repo/
          cd www-repo
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync /www/ directory from master"
          else
            echo "No changes to commit"
          fi

      - name: Push changes to www branch
        run: |
          cd www-repo
          if [ -n "$(git status --porcelain)" ]; then
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin www
          else
            echo "No changes to commit"
          fi
